version: '3.3'
services:
  bitcoin-testnet:
    build:
      context: ./
      dockerfile: Dockerfile
    command: bitcoind -testnet
    deploy:
      endpoint_mode: vip
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 10s
      placement:
        constraints: [node.hostname == vm01]
    image: testing.wemic.io:5000/cryptochain/bitcoin-testnet
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "10"
    networks:
      - web-services
    ports:
      - 18332:18332
      - 18333:18333

networks:
  web-services:
    external: true
